{% set version = "0.2.2" %}

package:
  name: graphvite-split
  version: {{ version }}

source:
  url: https://github.com/DeepGraphLearning/graphvite/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 81c0a55102051d2933d5b51dbf49e0b6faeefb2f503331b59484134e4db4586f
  patches:
    - patches/0001-allow-setting-CUDA_ARCHES-through-cmake-itself.patch
    - patches/0002-compile-with-c-17.patch
    - patches/0003-point-to-correct-faiss-lib.patch
    - patches/0004-add-install-step.patch
    - patches/0005-help-find-gflags-glog.patch
    - patches/0006-adapt-to-CUDA-12.patch       # [(cuda_compiler_version or "").startswith("12")]
    - patches/0007-adapt-to-faiss-1.7.4.patch

build:
  number: 3
  # only linux for now
  skip: true  # [not linux]
  skip: true  # [cuda_compiler_version == "None"]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}

outputs:
  # only difference between graphvite-mini and graphvite is the amout on runtime-deps
  - name: graphvite-mini
    script: build-pkg.sh

    build:
      string: "py{{ CONDA_PY }}cuda{{ cuda_compiler_version|replace(".", "") }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_cuda"
    requirements:
      build:
        - {{ compiler("cxx") }}
        - {{ stdlib('c') }}
        - {{ compiler("cuda") }}
        - cmake
        - ninja
        - glog
        - gflags
        - python
        - pybind11
      host:
        # make
        - glog
        - gflags
        - libfaiss
        - numpy
        - python
        - pybind11
        # setup
        - easydict
        - pyyaml
        - setuptools
        - six
      run:
        - glog
        - gflags
        - python
        - easydict
        - future
        - {{ pin_compatible('numpy') }}
        - psutil
        - pyyaml
        - six
    test:
      imports:
        - graphvite
        - graphvite.application
        - graphvite.graph
      commands:
        - graphvite baseline -h
        - graphvite new -h
        - graphvite run -h
        - graphvite visualize -h

  # only difference between graphvite-mini and graphvite is the amout on runtime-deps
  - name: graphvite
    requirements:
      run:
        - {{ pin_subpackage('graphvite-mini', exact=True) }}
        - imageio
        - matplotlib
        - nltk
        - pytorch *
        - scipy
        - torchvision
    # already tested for graphvite-mini
    test:
      imports:
        - graphvite

about:
  home: https://graphvite.io/
  license: Apache-2.0
  license_file: LICENSE
  summary: "GraphVite: A General and High-performance Graph Embedding System"
  dev_url: https://github.com/DeepGraphLearning/graphvite
  doc_url: https://graphvite.io/docs/latest/index.html

extra:
  recipe-maintainers:
    - h-vetinari
  feedstock-name: graphvite
